### ISSUE TITLE
Formatting LogRecord message before posting to Slack

### ISSUE THREAD

**Issue by cvng** [mathiasose/slacker_log_handler#13]
Since we're using [#slack](https://slack.com/) for logging, it would be nice to have the ability to format messages before posting.

This can be achieved by exposing `message` in a function we can subclass.
https://github.com/mathiasose/slacker_log_handler/blob/master/slacker_log_handler/__init__.py#L32

```python
class SlackerLogHandler(Handler):
    def build_msg(self, record):
        return record.getMessage()

    def emit(self, record):
        message = str(self.build_msg(record))
        # [...]
```

```python
class CustomLogHandler(SlackerLogHandler):
    def build_msg(self, record):
        message = "> New message :\n" + record.getMessage()
        return message
```

And for the settings :

```python
LOGGING = {
    # [...]
    'handlers': {
        'slack-info': {
            # [...]
            'class': 'path.to.my.CustomLogHandler',
        },
    },
}
```

https://docs.python.org/3/library/logging.html#logging.LogRecord
https://get.slack.help/hc/en-us/articles/202288908-Format-your-messages

I can open a PR if needed 👍

**Comment by mathiasose** [comment]
Sounds like a good idea, if you want to make a PR then be go ahead.

**Comment by cvng** [comment]
Here is the patch. I also added a small example in the `README` for convenience.

**Comment by mathiasose** [comment]
Thanks, PR merged and up on pypi now.

**Comment by cvng** [comment]
Great, thanks !
