### ISSUE TITLE
Catch invalid API_KEY

### ISSUE THREAD

**Issue by kevincobain2000** [mathiasose/slacker_log_handler#15]
https://github.com/mathiasose/slacker_log_handler/blob/master/slacker_log_handler/__init__.py#L27

Slacker throws an error where there is invalid API_KEY. It'd be nice to be able to handle this error or not throw error, without it complete app collapses

**Comment by mathiasose** [comment]
I've been thinking about the best way to handle this.
Crashing the app is bad, but so is failing silently.
And logging the error may cause an infinite loop depending on the log configuration.

I made a PR with the *option* for failing silently that must be explicitly enabled.
Going to leave it unmerged for a few more days in case someone comments with a better solution.

**Comment by kevincobain2000** [comment]
>I've been thinking about the best way to handle this.
>Crashing the app is bad, but so is failing silently.

https://django-slack.readthedocs.io/#slack-fail-silently

```
Fail silently && !DEBUG
    // don't crash
```
