### ISSUE TITLE
Mention specific user/channel on error/fatal?

### ISSUE THREAD

**Issue by d33tah** [mathiasose/slacker_log_handler#20]
I'd like Slacker to shout to everyone on the channel (or at least to me) when an error happens. Is that possible?

**Comment by mathiasose** [comment]
Oh, for some reason I didn't see this in my feed when you posted it 20 days ago.

I'll see if I have time to test your PRs and merge after work today.

**Comment by mathiasose** [comment]
Thanks for the PRs @d33tah. I merged both and modified #23 to allow for a list of users instead of just one.

Things seemed to work as expected when I tested it, so I put it up on pypi as `v1.7.0`.
Please test it yourself and let me know if something doesn't work as expected.

**Comment by mathiasose** [comment]
Note to self: remember to add documentation for these new options later.
