### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by abawchen** [mathiasose/slacker_log_handler#30]
Hi, :)

This is a great library, but the latest commit is almost 1 year ago, wondering this project is still alive or not.

Thanks.

**Comment by reinoldus** [comment]
Also interested, but I assume it is a no if there is no comment for over a year on this issue

**Comment by mathiasose** [comment]
I'm a bit annoyed with github that I haven't noticed these issues and PRs even though I'm on the site almost every day to work on other repos.

As you can tell, I don't use the package any more myself. And https://github.com/os/slacker is archived. So it's pretty much dead, yeah.

I did merge the last two PRs and create a release. Slack won't let me create a new api key, so I can't even test it myself, but the code changes looked sensible enough. If anyone has any problems with the new release try tagging me @mathiasose and maybe github will notify me :upside_down_face:
